import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {AutoComplete, Button, Col, Input, Layout, Row, SelectProps, Typography } from "antd";
import {queryHouseListByKeyWord} from "@/lianjia-service/LianjiaService";
import {useState} from "react";
import {LianjiaSearchBar} from "@/views/LianjiaSearchBar";

const inter = Inter({ subsets: ['latin'] })

export const getServerSideProps =  (async () => {
  // const res = await fetch('https://api.github.com/repos/vercel/next.js')
  // const repo = await res.json()

  return { props: { result:'' } }
})


// @ts-ignore
export default function Home() {


    return (
    <>
      <Head>
        <title>Lianjia搜索</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Layout style={{backgroundColor:'#FFFFFF'}}>
              <Layout.Content>

                  <Col>
                      <Row style={{marginTop: '50%', flex: 1, justifyContent:'center'}}>
                          <Typography.Title>Lianjia Search</Typography.Title>
                      </Row>
                      <Row>
                          <LianjiaSearchBar></LianjiaSearchBar>
                      </Row>

                  </Col>
              </Layout.Content>
          </Layout>

      </main>
    </>
  )
}
