import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {AutoComplete, Button, Col, FloatButton, Input, Layout, Row, SelectProps, Typography} from "antd";
import {queryHouseListByKeyWord} from "@/lianjia-service/LianjiaService";
import React, {useState} from "react";
import {LianjiaSearchBar} from "@/views/LianjiaSearchBar";
import {useRouter} from "next/router";
import {router} from "next/client";
import {CalendarOutlined, UserOutlined} from "@ant-design/icons";
import {useUser} from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ['latin'] })

export const getServerSideProps =  (async () => {
  // const res = await fetch('https://api.github.com/repos/vercel/next.js')
  // const repo = await res.json()

  return { props: { result:'' } }
})


// @ts-ignore
export default function Home() {

    const router = useRouter()
    const { user, error, isLoading } = useUser();

    return (
    <>
      <Head>
        <title>Lianjia搜索</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Layout style={{backgroundColor:'#FFFFFF'}}>
              <Layout.Content>
                  <Col xs={{span:24, offset:0}} sm={{span:24, offset:0}} md={{span:18, offset:3}} lg={{span:10, offset:7}} xl={{span:8, offset:8}} >
                      <Row style={{marginTop: '50%', flex: 1, justifyContent:'center'}}>
                          <Typography.Title>Lianjia Search</Typography.Title>
                      </Row>
                      <Row>
                          <LianjiaSearchBar onSearch={(value:string) => {
                              router.push(`/searchlist/${value}`)
                          }}></LianjiaSearchBar>
                      </Row>

                  </Col>
                  <FloatButton.Group>
                      <FloatButton onClick={() => router.push('/profile')}  icon={<UserOutlined/>}/>
                      <FloatButton
                          icon={<CalendarOutlined />}
                          onClick={() => {router.push('/compare')}}/>
                  </FloatButton.Group>
              </Layout.Content>
          </Layout>

      </main>
    </>
  )
}
